### ISSUE TITLE
apache_get_modules does not work with PHP-FPM

### ISSUE THREAD

**Issue by nichtmax** [typemill/typemill#32]
The setup process does not work when [PHP-FPM](https://manual.uberspace.de/lang-php.html#connection-to-webserver) is used:

```
Slim Application Error
The application could not run because of the following error:

Details

Type: Error
Message: Call to undefined function Typemill\Controllers\apache_get_modules()
File: /var/www/virtual/ertt/wiki.philipp-kranich.de/system/Controllers/SetupController.php
Line: 33
Trace

#0 [internal function]: Typemill\Controllers\SetupController->show(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#1 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/Middleware/ValidationErrorsMiddleware.php(27): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 [internal function]: Typemill\Middleware\ValidationErrorsMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#8 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\Middleware\ValidationErrorsMiddleware), Array)
#9 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#10 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#11 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/Middleware/OldInputMiddleware.php(29): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: Typemill\Middleware\OldInputMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#13 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\Middleware\OldInputMiddleware), Array)
#14 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#15 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#16 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/csrf/src/Guard.php(171): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 [internal function]: Slim\Csrf\Guard->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#18 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Slim\Csrf\Guard), Array)
#19 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#20 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#21 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#22 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#23 /var/www/virtual/ertt/wiki.philipp-kranich.de/system/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#24 /var/www/virtual/ertt/wiki.philipp-kranich.de/index.php(7): Slim\App->run()
#25 {main}
```

mod_rewrite and htaccess are both installed, tested with PHP 7.1 and Apache 2.4 on a fresh [Uberspace](uberspace.de) account. PHP-FPM is pretty common, is there any way you could change the detection? I didn't dig deep but found [this issue](https://github.com/nette/examples/issues/17) at another project.

**Comment by Frontend-Head** [comment]
I have the same error message. I have just installed Typemill and as soon as I want to go to /setup I get it: 
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

The Settings folder is empty.

**Comment by trendschau** [comment]
Thank you for the finding!! 

I will fix or remove this check with the next version. You can either skip this version or, if you don't want to wait, just remove these lines 32 - 37 lines from the setup-Controller:

```
		# check if mod rewrite is enabled
		$modules = apache_get_modules();
		if(!in_array('mod_rewrite', $modules))
		{
			$systemcheck['error'][] = 'The apache module "mod_rewrite" is not enabled.';
		}
```

Here: https://github.com/typemill/typemill/blob/master/system/Controllers/SetupController.php

**Comment by trendschau** [comment]
I deleted this check in version 1.2.18 (just published).
