### ISSUE TITLE
Plugins cannot be managed after update to 1.5.3.3

### ISSUE THREAD

**Issue by DSigmund** [typemill/typemill#345]
In the admin-page, the link produces an error page:

`Deprecated: Return type of Slim\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 112

Deprecated: Return type of Slim\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 124

Deprecated: Return type of Slim\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 135

Deprecated: Return type of Slim\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 145

Deprecated: Return type of Slim\Collection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 155

Deprecated: Return type of Slim\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 165

Deprecated: preg_replace_callback(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Http/Uri.php on line 717

Deprecated: preg_replace_callback(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Http/Uri.php on line 717

Deprecated: Return type of Slim\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 112

Deprecated: Return type of Slim\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 124

Deprecated: Return type of Slim\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 135

Deprecated: Return type of Slim\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 145

Deprecated: Return type of Slim\Collection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 155

Deprecated: Return type of Slim\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/slim/Slim/Collection.php on line 165

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/system.php on line 195

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/system.php on line 196

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/system.php on line 200

Warning: session_name(): Session name cannot be changed after headers have already been sent in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/system.php on line 201

Warning: session_start(): Session cannot be started after headers have already been sent in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/system.php on line 229

Fatal error: Uncaught RuntimeException: Flash messages middleware failed. Session not found. in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/flash/src/Messages.php:66 Stack trace: #0 /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/system.php(225): Slim\Flash\Messages->__construct() #1 /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/pimple/pimple/src/Pimple/Container.php(122): {closure}() #2 /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/system.php(300): Pimple\Container->offsetGet() #3 /var/www/vhosts/webdad.eu/dsofm.webdad.eu/index.php(5): require('...') #4 {main} thrown in /var/www/vhosts/webdad.eu/dsofm.webdad.eu/system/vendor/slim/flash/src/Messages.php on line 66`

PHP-Version: 8.1.5

**Comment by DSigmund** [comment]
Also with php 8.0.18

**Comment by DSigmund** [comment]
After manual update of all plugins it works again
