### ISSUE TITLE
Docker Container Media Upload not working

### ISSUE THREAD

**Issue by grugel-maintro** [typemill/typemill#392]
For some reason the file upload does not work at all for me. I was building the image locally and I'm not getting any indication for errors in the docker container logs.

**Comment by TildeSlashC0re** [comment]
experiencing the same... here's the ERROR 500 from the application handling a media-upload

```
172.17.0.1 - - [13/Oct/2023:13:16:42 +0000] "POST /api/v1/image HTTP/1.0" 500 357 "https:// *   *   *   *   * /tm/content/visual/entries/00-log-0" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
```

```php
[Fri Oct 13 13:16:42.283063 2023] [php:notice] [pid 21] [client 172.17.0.1:42690] Slim Application Error:\nType: TypeError\nMessage: imagesx(): Argument #1 ($image) must be of type GdImage, bool given\nFile: /var/www/html/system/Models/ProcessImage.php\nLine: 163\nTrace: #0 /var/www/html/system/Models/ProcessImage.php(163): imagesx(false)\n#1 /var/www/html/system/Models/ProcessImage.php(45): Typemill\\Models\\ProcessImage->getImageSize(false)\n#2 /var/www/html/system/Controllers/ControllerAuthorMediaApi.php(198): Typemill\\Models\\ProcessImage->createImage(false, 'hero-log-0.jpg', Array)\n#3 [internal function]: Typemill\\Controllers\\ControllerAuthorMediaApi->createImage(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#4 /var/www/html/system/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#5 /var/www/html/system/vendor/slim/slim/Slim/Route.php(281): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#6 /var/www/html/system/Middleware/RestrictApiAccess.php(30): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#7 [internal function]: Typemill\\Middleware\\RestrictApiAccess->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))\n#8 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\\Middleware\\RestrictApiAccess), Array)\n#9 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))\n#10 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))\n#11 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#12 /var/www/html/system/vendor/slim/slim/Slim/Route.php(268): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#13 /var/www/html/system/vendor/slim/slim/Slim/App.php(503): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#14 /var/www/html/system/Middleware/ValidationErrorsMiddleware.php(34): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#15 [internal function]: Typemill\\Middleware\\ValidationErrorsMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#16 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\\Middleware\\ValidationErrorsMiddleware), Array)\n#17 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#18 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#19 /var/www/html/system/Middleware/SecurityMiddleware.php(114): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#20 [internal function]: Typemill\\Middleware\\securityMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#21 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\\Middleware\\securityMiddleware), Array)\n#22 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#23 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#24 /var/www/html/system/Middleware/OldInputMiddleware.php(29): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#25 [internal function]: Typemill\\Middleware\\OldInputMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#26 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\\Middleware\\OldInputMiddleware), Array)\n#27 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#28 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#29 /var/www/html/system/vendor/slim/csrf/src/Guard.php(171): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#30 [internal function]: Slim\\Csrf\\Guard->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#31 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Slim\\Csrf\\Guard), Array)\n#32 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#33 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#34 /var/www/html/system/Middleware/assetMiddleware.php(43): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#35 [internal function]: Typemill\\Middleware\\assetMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#36 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\\Middleware\\assetMiddleware), Array)\n#37 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#38 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#39 /var/www/html/system/vendor/akrabat/proxy-detection-middleware/src/ProxyDetection.php(66): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#40 [internal function]: RKA\\Middleware\\ProxyDetection->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#41 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(RKA\\Middleware\\ProxyDetection), Array)\n#42 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#43 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#44 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#45 /var/www/html/system/vendor/slim/slim/Slim/App.php(392): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#46 /var/www/html/system/vendor/slim/slim/Slim/App.php(297): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#47 /var/www/html/index.php(7): Slim\\App->run()\n#48 {main}\nView in rendered output by enabling the "displayErrorDetails" setting.\n, referer: https://c0re.dev/tm/content/visual/entries/00-log-0
```
