### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by b42n1** [typemill/typemill#393]
I installed Typemill using the [official Docker image](https://github.com/typemill/typemill#docker) and everything worked smoothly when I accessed it using my local IP and port. However, when I exposed Typemill with Nginx Proxy Manager and Cloudflare as my DNS, the frontend worked fine, but I encountered an error message after attempting to log in.

```
Slim Application Error

The application could not run because of the following error:
Details
Type: Error
Message: Call to undefined function imagettfbbox()
File: /var/www/html/system/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php
Line: 345
Trace

#0 /var/www/html/system/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php(459): Gregwar\Captcha\CaptchaBuilder->writePhrase(Object(GdImage), 'xTHV7', '/var/www/html/s...', 150, 40)
#1 /var/www/html/system/Extensions/TwigCaptchaExtension.php(22): Gregwar\Captcha\CaptchaBuilder->build()
#2 /var/www/html/system/vendor/twig/twig/src/Environment.php(418) : eval()'d code(128): Typemill\Extensions\TwigCaptchaExtension->captchaImage(Array)
#3 /var/www/html/system/vendor/twig/twig/src/Template.php(182): __TwigTemplate_d4b22b17b2384afecdb81ae317b7f412bae1b3c3cdadb1967c5fad537b3cccee->block_content(Array, Array)
#4 /var/www/html/system/vendor/twig/twig/src/Environment.php(418) : eval()'d code(114): Twig\Template->displayBlock('content', Array, Array)
#5 /var/www/html/system/vendor/twig/twig/src/Template.php(405): __TwigTemplate_28292d0a0eaf168dcad24c9d647db2adbd9bb238601d74a36699e327c79de10b->doDisplay(Array, Array)
#6 /var/www/html/system/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /var/www/html/system/vendor/twig/twig/src/Environment.php(418) : eval()'d code(43): Twig\Template->display(Array, Array)
#8 /var/www/html/system/vendor/twig/twig/src/Template.php(405): __TwigTemplate_d4b22b17b2384afecdb81ae317b7f412bae1b3c3cdadb1967c5fad537b3cccee->doDisplay(Array, Array)
#9 /var/www/html/system/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /var/www/html/system/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#11 /var/www/html/system/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#12 /var/www/html/system/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#13 /var/www/html/system/vendor/slim/twig-view/src/Twig.php(92): Twig\Environment->render('/auth/login.twi...', Array)
#14 /var/www/html/system/vendor/slim/twig-view/src/Twig.php(136): Slim\Views\Twig->fetch('/auth/login.twi...', Array)
#15 /var/www/html/system/Controllers/ControllerShared.php(78): Slim\Views\Twig->render(Object(Slim\Http\Response), '/auth/login.twi...', Array)
#16 /var/www/html/system/Controllers/ControllerFrontendAuth.php(41): Typemill\Controllers\ControllerShared->render(Object(Slim\Http\Response), '/auth/login.twi...', Array)
#17 [internal function]: Typemill\Controllers\ControllerFrontendAuth->show(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#18 /var/www/html/system/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#19 /var/www/html/system/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#20 /var/www/html/system/Middleware/RedirectIfAuthenticated.php(28): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#21 [internal function]: Typemill\Middleware\RedirectIfAuthenticated->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#22 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\Middleware\RedirectIfAuthenticated), Array)
#23 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#24 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#25 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#26 /var/www/html/system/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#27 /var/www/html/system/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#28 /var/www/html/system/Middleware/ValidationErrorsMiddleware.php(34): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#29 [internal function]: Typemill\Middleware\ValidationErrorsMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#30 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\Middleware\ValidationErrorsMiddleware), Array)
#31 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#32 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#33 /var/www/html/system/Middleware/SecurityMiddleware.php(114): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#34 [internal function]: Typemill\Middleware\securityMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#35 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\Middleware\securityMiddleware), Array)
#36 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#37 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#38 /var/www/html/system/Middleware/OldInputMiddleware.php(29): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#39 [internal function]: Typemill\Middleware\OldInputMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#40 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\Middleware\OldInputMiddleware), Array)
#41 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#42 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#43 /var/www/html/system/vendor/slim/csrf/src/Guard.php(171): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#44 [internal function]: Slim\Csrf\Guard->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#45 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Slim\Csrf\Guard), Array)
#46 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#47 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#48 /var/www/html/system/Middleware/assetMiddleware.php(36): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#49 [internal function]: Typemill\Middleware\assetMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#50 /var/www/html/system/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Typemill\Middleware\assetMiddleware), Array)
#51 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#52 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#53 /var/www/html/system/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#54 /var/www/html/system/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#55 /var/www/html/system/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#56 /var/www/html/index.php(7): Slim\App->run()
#57 {main}
```

**Comment by barnabashohl** [comment]
Sometimes it's the small that can cause the biggest problems. I had been experimenting with so many different things that I forgot to check the basics. As it turns out, the wrong password had been saved in my password manager. So, if you're experiencing the same issue, be sure to double-check your user information. :)

**Comment by trendschau** [comment]
Thank you for the solution and sorry for not replying. I am cleaning up the issues now and this seems to be solved :)
